### ISSUE TITLE
Allow non-interactive install of fetch apply

### ISSUE THREAD

**Issue by emmetog** [P5vc/FetchApply#1]
The currently recommended way to install fetch apply is to download https://raw.githubusercontent.com/P5vc/FetchApply/master/install and run it interactively, answering questions as they come up. It's not possible at the moment to run it non-interactively.

A possible solution would be to allow passing all options as arguments on the command line, for example:

```bash
bash /tmp/install --install-path=/var/lib --log-file=/var/log/fetchapply.log --git-url=https://github.com/P5vc/ServerConfigurations.git --cron-frequency="10 1 * * *"
```
A `--non-interactive` flag could also be used to tell the installer to take default values when they are not specified, instead of interactively asking the user if it's not specified. This would mean that all values would be taken as defaults unless overridden using the command line argument as described above.

**Comment by P5vc** [comment]
Thank you for the suggestion! This is a great idea! We'll be sure to implement this change within a few days. :+1:

**Comment by P5vc** [comment]
@emmetog Once again, thank you for the suggestion! The change has now been implemented! Feel free to test it out and let us know what you think.

As a thank you for contributing (https://github.com/P5vc/Documentation/blob/master/Contributing/contributionGuide.md#perks-of-contributing), you're eligible for 30 days of a free, @P5.vc email and 30 days with a free, premium Priveasy Docs account. If you're interested, just respond on this thread and we'll hook you up. :+1:

**Comment by emmetog** [comment]
@P5vc thanks! I'm using the new install script and it works a treat, thanks!
